kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  name: subscriptions.operators.coreos.com
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: web-terminal
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: web-terminal.v1.6.0