apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ldap
  finalizers:
  - kubernetes.io/pvc-protection
  name: ldap
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5G
  storageClassName: gp2
  volumeMode: Filesystem
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ldap
    app.kubernetes.io/component: ldap
    app.kubernetes.io/instance: ldap
  annotations:
    checkov.io/skip1: CKV_K8S_43=Demo/Workshop environment, we don't need a fixed hash.
    checkov.io/skip2: CKV_K8S_15=Demo/Workshop environment, we don't need to allways pull the image.
    checkov.io/skip3: CKV_K8S_22=Demo/Workshop environment, not necessary to enforce read-only filesystem.
    checkov.io/skip4: CKV_K8S_40=OpenShift will assign a random UUID for the User.
    checkov.io/skip5: CKV_K8S_31=Demo/Workshop environment, not necessary to enforce a seccomp profile.
    checkov.io/skip6: CKV_K8S_11=Demo/Workshop environment, CPU limits can be ignored.
    checkov.io/skip7: CKV_K8S_13=Demo/Workshop environment, Memory limits can be ignored.
    checkov.io/skip8: CKV_K8S_21=Demo/Workshop environment, Usage of default namespace is fine.
    checkov.io/skip9: CKV2_K8S_6=Demo/Workshop environment, not necessary to drop capabilities.
  name: ldap
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: ldap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: ldap
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: LDAP_ROOT
          valueFrom:
            configMapKeyRef:
              key: LDAP_ROOT
              name: ldap
        - name: LDAP_USERS
          valueFrom:
            configMapKeyRef:
              key: LDAP_USERS
              name: ldap
        - name: LDAP_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: LDAP_ADMIN_PASSWORD
              name: ldap
        - name: LDAP_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              key: LDAP_ADMIN_USERNAME
              name: ldap
        - name: LDAP_PASSWORDS
          valueFrom:
            configMapKeyRef:
              key: LDAP_PASSWORDS
              name: ldap
        image: bitnami/openldap:2.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 1389
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 1389
          timeoutSeconds: 1
        name: ldap
        ports:
        - containerPort: 1389
          protocol: TCP
        - containerPort: 1636
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/openldap
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ldap
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap
    app.kubernetes.io/component: ldap
    app.kubernetes.io/instance: ldap
  annotations:
    checkov.io/skip8: CKV_K8S_21=Demo/Workshop environment, Usage of default namespace is fine.
  name: ldap
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ldap
    port: 1389
    protocol: TCP
    targetPort: 1389
  - name: ldaps
    port: 1636
    protocol: TCP
    targetPort: 1636
  selector:
    deployment: ldap
  sessionAffinity: None
  type: ClusterIP
status: {}
