---
# Service A deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: aws-xray
  annotations:
    checkov.io/skip1: CKV_K8S_9=Demo/Workshop environment, skip readiness probe.
    checkov.io/skip2: CKV_K8S_31=Demo/Workshop environment, not necessary to enforce a seccomp profile.
    checkov.io/skip3: CKV_K8S_14=Application container only available with latest tag.
    checkov.io/skip4: CKV_K8S_22=Demo/Workshop environment, not necessary to enforce read-only filesystem.
    checkov.io/skip5: CKV_K8S_43=Demo/Workshop environment, we don't need a fixed hash.
    checkov.io/skip6: CKV_K8S_8=Demo/Workshop environment, skip liveness probe.
    checkov.io/skip7: CKV_K8S_40=OpenShift will assign a random UUID for the User.
    checkov.io/skip8: CKV_K8S_29=False positive, security context defined.
    checkov.io/skip9: CKV_K8S_21=Demo/Workshop environment, Usage of default namespace is fine.
    checkov.io/skip10: CKV2_K8S_6=Demo/Workshop environment, not necessary to drop capabilities.
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: service-a
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: service-a
    spec:
      automountServiceAccountToken: false
      containers:
        - name: service-a
          image: ckassen/aws-xray-kubernetes-service-a:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: API_CNAME
              value: service-b.aws-xray
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: xray-service.aws-xray:2000
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
            limits:
              cpu: 1024m
              memory: 128Mi

---
# Service A
apiVersion: v1
kind: Service
metadata:
  name: service-a
  annotations:
    checkov.io/skip9: CKV_K8S_21=Demo/Workshop environment, Usage of default namespace is fine.
spec:
  selector:
    app: service-a
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http

###
---
# Service B
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: aws-xray
  annotations:
    checkov.io/skip1: CKV_K8S_9=Demo/Workshop environment, skip readiness probe.
    checkov.io/skip2: CKV_K8S_31=Demo/Workshop environment, not necessary to enforce a seccomp profile.
    checkov.io/skip3: CKV_K8S_14=Application container only available with latest tag.
    checkov.io/skip4: CKV_K8S_22=Demo/Workshop environment, not necessary to enforce read-only filesystem.
    checkov.io/skip5: CKV_K8S_43=Demo/Workshop environment, we don't need a fixed hash.
    checkov.io/skip6: CKV_K8S_8=Demo/Workshop environment, skip liveness probe.
    checkov.io/skip7: CKV_K8S_40=OpenShift will assign a random UUID for the User.
    checkov.io/skip8: CKV_K8S_29=False positive, security context defined.
    checkov.io/skip9: CKV_K8S_21=Demo/Workshop environment, Usage of default namespace is fine.
    checkov.io/skip10: CKV2_K8S_6=Demo/Workshop environment, not necessary to drop capabilities.
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: service-b
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: service-b
    spec:
      automountServiceAccountToken: false
      containers:
        - name: service-b
          image: ckassen/aws-xray-kubernetes-service-b:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: AWS_XRAY_DAEMON_ADDRESS
              value: xray-service.aws-xray:2000
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
            limits:
              cpu: 1024m
              memory: 128Mi

---
# Service B
apiVersion: v1
kind: Service
metadata:
  name: service-b
  annotations:
    checkov.io/skip9: CKV_K8S_21=Demo/Workshop environment, Usage of default namespace is fine.
spec:
  selector:
    app: service-b
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
